Landing page schema docs
RedHatInsights/landing-page-frontend pull request #310
Opened 2021-05-11 09:02 UTC by Hyperkid123

jira: https://issues.redhat.com/browse/RHCLOUD-14079

### Changes
- added content schema validator
- fixed misconfigured tiles
- added docs for each tile type shape

2021-05-11 15:11 UTC, ryelo requested changes

2021-05-11 15:11 UTC, ryelo commented on docs/content-schema.md
> +  condition?: Condition // see bellow
This happens in a few places

2021-05-11 15:13 UTC, Hyperkid123 commented on docs/content-schema.md
> +  condition?: Condition // see bellow
copy pasta :wink:

2021-05-12 07:56 UTC, karelhala approved these changes

2021-05-14 07:09 UTC, merged